
SRC_LIBPHANTOM = phantom/libphantom/console_color.c \
								 phantom/libphantom/wired_spin.c \
								 phantom/libphantom/udp_json_builder.c \
								 phantom/libphantom/atoin.c \
								 phantom/libphantom/init.c \
								 phantom/libphantom/i_disk.c \
								 phantom/libphantom/hashfunc.c \
								 phantom/libphantom/udp_json.c \
								 phantom/libphantom/pool.c \
								 phantom/libphantom/hexdump.c \
								 phantom/libphantom/json_read.c \
								 phantom/libphantom/asn1.c \
								 phantom/libphantom/atoln.c \
								 phantom/libphantom/unicode2utf8.c \
								 phantom/libphantom/disk_struct.c \
								 phantom/libphantom/debug.c \
								 phantom/libphantom/symtab.c \
								 phantom/libphantom/jsmn.c \
								 phantom/libphantom/stats.c \
								 phantom/libphantom/json_write.c \
								 phantom/libphantom/http.c \
								 phantom/libphantom/wtty.c \
								 phantom/libphantom/video/color.c \
								 phantom/libphantom/lzma/LzmaDec.c \
								 phantom/libphantom/lzma/simpleDecode.c \
								 phantom/libphantom/unix/fname.c

SRC_C += $(SRC_LIBPHANTOM)