SRC_PHANTOM_LIBC =  phantom/isomem/contrib/bcd.c \
					phantom/isomem/contrib/index.c \
					phantom/isomem/contrib/rindex.c \
					phantom/isomem/contrib/strcat.c \
					phantom/isomem/contrib/strchr.c \
					phantom/isomem/contrib/strcmp.c \
					phantom/isomem/contrib/strcpy.c \
					phantom/isomem/contrib/strdup.c \
					phantom/isomem/contrib/strlcat.c \
					phantom/isomem/contrib/strlcpy.c \
					phantom/isomem/contrib/strlen.c \
					phantom/isomem/contrib/strncat.c \
					phantom/isomem/contrib/strncmp.c \
					phantom/isomem/contrib/strncpy.c \
					phantom/isomem/contrib/strnlen.c \
					phantom/isomem/contrib/strrchr.c \
					phantom/isomem/contrib/strstr.c \
					phantom/isomem/contrib/subr_prf.c \
					phantom/isomem/contrib/subr_scanf.c


SRC_C += $(SRC_PHANTOM_LIBC)