SRC_GL = phantom/gl/specbuf.c \
				phantom/gl/phantom_loop.c \
				phantom/gl/list.c \
				phantom/gl/error.c \
				phantom/gl/texture.c \
				phantom/gl/select.c \
				phantom/gl/init.c \
				phantom/gl/light.c \
				phantom/gl/arrays.c \
				phantom/gl/vertex.c \
				phantom/gl/oscontext.c \
				phantom/gl/image_util.c \
				phantom/gl/clip.c \
				phantom/gl/phantomdrvr.c \
				phantom/gl/api.c \
				phantom/gl/misc.c \
				phantom/gl/memory.c \
				phantom/gl/clear.c \
				phantom/gl/zdither.c \
				phantom/gl/msghandling.c \
				phantom/gl/ztriangle.c \
				phantom/gl/zline.c \
				phantom/gl/zmath.c \
				phantom/gl/zbuffer.c \
				phantom/gl/matrix.c \
				phantom/gl/texobj.c \
				phantom/gl/get.c

SRC_C += $(SRC_GL)